# Generated by Django 5.2.8 on 2025-11-24 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_portfolio', '0003_alter_meroshareholding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ASSET', 'Asset (Cash/Bank)'), ('LIABILITY', 'Liability (Loans/Payables)'), ('EQUITY', 'Equity'), ('INCOME', 'Income (Dividends/Profit)'), ('EXPENSE', 'Expense (Fees/Charges)')], max_length=20)),
                ('broker_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('sanctioned_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Loan Sanction Date')),
                ('expiry_date', models.DateField(blank=True, help_text='Renewal/Expiry Date', null=True)),
                ('current_used_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Loan Facilities',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('ref_id', models.CharField(blank=True, max_length=50)),
                ('entry_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_settled', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting_desk.accounthead')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanInterestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.FloatField(default=0.0, help_text="Bank's Base Rate %")),
                ('premium', models.FloatField(default=0.0, help_text='Agreed Premium %')),
                ('rate', models.FloatField(editable=False, help_text='Total Effective Rate %')),
                ('effective_date', models.DateField(verbose_name='From Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_history', to='accounting_desk.loanfacility')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PledgedScrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valuation_percent', models.FloatField(default=50)),
                ('allowable_drawing_power', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('demat_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_portfolio.demataccount')),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledged_scrips', to='accounting_desk.loanfacility')),
            ],
        ),
        migrations.CreateModel(
            name='PledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('symbol', models.CharField(max_length=20, verbose_name='Script')),
                ('action', models.CharField(choices=[('BALANCE', 'Balance b/d'), ('PLEDGE', 'Pledge (Add)'), ('UNPLEDGE', 'Unpledged (Release)')], max_length=10)),
                ('margin', models.FloatField(default=50, verbose_name='Margin %')),
                ('kitta', models.PositiveIntegerField(verbose_name='Kitta (Qty)')),
                ('average_closing_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilized_loan', models.DecimalField(decimal_places=2, default=0, help_text='Amount Utilized or Repaid', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demat_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_portfolio.demataccount')),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_entries', to='accounting_desk.loanfacility', verbose_name='Pledged Institution')),
            ],
            options={
                'verbose_name': 'Entry Sheet Row',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
