# Generated by Django 5.2.8 on 2025-11-25 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listed_companies', '0003_corporateaction_lockinperiod_shareholdingpattern'),
        ('my_portfolio', '0003_alter_meroshareholding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Loan A/C No')),
                ('sanctioned_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Sanctioned Limit')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sanction Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1. Bank Facility Entry',
                'verbose_name_plural': '1. Bank Facility Entries',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='LoanInterestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Effective Date')),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Base Rate %')),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Premium %')),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_entries', to='accounting_desk.loanfacility', verbose_name='Bank')),
            ],
            options={
                'verbose_name': '2. Interest Rate Entry',
                'verbose_name_plural': '2. Interest Rate Entries',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PledgeEntrySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=50, unique=True, verbose_name='Unique ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('action', models.CharField(choices=[('BALANCE_BD', 'Balance b/d (Opening)'), ('PLEDGE', 'Pledge (Deposit)'), ('UNPLEDGE', 'Unpledge (Release)'), ('VALUATION', 'Valuation Update')], max_length=20, verbose_name='Action')),
                ('kitta', models.IntegerField(default=0, help_text='Qty for this transaction', verbose_name='Kitta')),
                ('tx_utilized', models.DecimalField(decimal_places=2, default=0, help_text='Loan amount Taken or Repaid', max_digits=15, verbose_name='Utilized Amt')),
                ('tx_180_avg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='180 Days Avg')),
                ('tx_closing_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Closing Price (CP)')),
                ('tx_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margin %')),
                ('tx_min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min Price')),
                ('tx_drawing_power', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Drawing Amt')),
                ('cl_kitta', models.IntegerField(default=0, editable=False)),
                ('cl_drawing_power', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('cl_utilized', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demat_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_portfolio.demataccount', verbose_name='DP / Demat')),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_entries', to='accounting_desk.loanfacility', verbose_name='Bank')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listed_companies.companies', to_field='script_ticker', verbose_name='Script')),
            ],
            options={
                'verbose_name': '4. Pledge Entry Sheet',
                'verbose_name_plural': '4. Pledge Entry Sheets',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarginRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Margin %')),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_entries', to='accounting_desk.loanfacility', verbose_name='Bank')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listed_companies.companies', to_field='script_ticker', verbose_name='Script')),
            ],
            options={
                'verbose_name': '3. Margin Entry',
                'verbose_name_plural': '3. Margin Entries',
                'ordering': ['symbol'],
                'unique_together': {('loan_facility', 'symbol')},
            },
        ),
    ]
