# Generated by Django 5.2.8 on 2025-11-23 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ASSET', 'Asset (Cash/Bank)'), ('LIABILITY', 'Liability (Loans/Payables)'), ('EQUITY', 'Equity'), ('INCOME', 'Income (Dividends/Profit)'), ('EXPENSE', 'Expense (Fees/Charges)')], max_length=20)),
                ('broker_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='e.g. Nabil Bank, Global IME', max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('sanctioned_limit', models.DecimalField(decimal_places=2, help_text='Total limit approved by bank', max_digits=15)),
                ('interest_rate', models.FloatField(help_text='Current/Initial Annual Interest Rate %')),
                ('current_used_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total loan amount currently utilized', max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Loan Facilities',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('ref_id', models.CharField(blank=True, help_text='Cheque No / Transaction ID', max_length=50)),
                ('entry_type', models.CharField(choices=[('DR', 'Debit (Money In/Expense)'), ('CR', 'Credit (Money Out/Income)')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_settled', models.BooleanField(default=True, help_text='Uncheck if this is a pending receivable/payable')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting_desk.accounthead')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanInterestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(help_text='The new interest rate (e.g., 12.5)')),
                ('effective_date', models.DateField(help_text='Date from when this rate is applicable')),
                ('remarks', models.CharField(blank=True, help_text='e.g. Base Rate Increase', max_length=200)),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_history', to='accounting_desk.loanfacility')),
            ],
            options={
                'verbose_name_plural': 'Loan Interest History',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PledgedScrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('pledged_date', models.DateField(default=django.utils.timezone.now)),
                ('valuation_percent', models.FloatField(default=50, help_text="Bank's valuation % (e.g., 50 for 50% margin)")),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledged_scrips', to='accounting_desk.loanfacility')),
            ],
        ),
    ]
