# Generated by Django 5.2.8 on 2025-11-23 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_desk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanfacility',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='loanfacility',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Renewal/Expiry Date', null=True),
        ),
        migrations.AddField(
            model_name='loanfacility',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Loan Sanction Date'),
        ),
        migrations.AddField(
            model_name='loaninteresthistory',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Date'),
        ),
        migrations.AlterField(
            model_name='loanfacility',
            name='bank_name',
            field=models.CharField(help_text='e.g. Nabil Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanfacility',
            name='current_used_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanfacility',
            name='sanctioned_limit',
            field=models.DecimalField(decimal_places=2, help_text='Total approved limit', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loaninteresthistory',
            name='effective_date',
            field=models.DateField(verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='loaninteresthistory',
            name='rate',
            field=models.FloatField(help_text='Interest Rate %'),
        ),
        migrations.AlterField(
            model_name='loaninteresthistory',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pledgedscrip',
            name='valuation_percent',
            field=models.FloatField(default=50, help_text="Bank's valuation %"),
        ),
    ]
