# Generated by Django 5.2.8 on 2025-11-24 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_desk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('script', models.CharField(max_length=20, verbose_name='Script')),
                ('margin', models.FloatField(help_text='Margin % (e.g., 50)')),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('loan_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_desk.loanfacility', verbose_name='Pledged Institution')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('loan_facility', 'script', 'date')},
            },
        ),
    ]
