# Generated by Django 5.2.8 on 2025-11-23 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_desk', '0002_remove_loanfacility_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaninteresthistory',
            options={'ordering': ['-effective_date']},
        ),
        migrations.AddField(
            model_name='loaninteresthistory',
            name='base_rate',
            field=models.FloatField(default=0.0, help_text="Bank's Base Rate %"),
        ),
        migrations.AddField(
            model_name='loaninteresthistory',
            name='premium',
            field=models.FloatField(default=0.0, help_text='Agreed Premium %'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='is_settled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='ref_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loanfacility',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loanfacility',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanfacility',
            name='sanctioned_limit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanfacility',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loaninteresthistory',
            name='rate',
            field=models.FloatField(editable=False, help_text='Total Effective Rate %'),
        ),
        migrations.AlterField(
            model_name='pledgedscrip',
            name='valuation_percent',
            field=models.FloatField(default=50),
        ),
    ]
