# Generated by Django 5.2.8 on 2025-11-23 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_desk', '0003_alter_loaninteresthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanfacility',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Renewal/Expiry Date', null=True),
        ),
        migrations.AlterField(
            model_name='loanfacility',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Loan Sanction Date'),
        ),
    ]
