# Generated by Django 5.2.8 on 2025-11-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_desk', '0004_alter_loanfacility_expiry_date_and_more'),
        ('my_portfolio', '0003_alter_meroshareholding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgedscrip',
            name='allowable_drawing_power',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='pledgedscrip',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Input: Average Closing Price (e.g. 180 days)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pledgedscrip',
            name='average_price_days',
            field=models.IntegerField(default=180, help_text='e.g. 120 or 180 days'),
        ),
        migrations.AddField(
            model_name='pledgedscrip',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest Closing Price from StockPrices', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pledgedscrip',
            name='demat_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_portfolio.demataccount'),
        ),
        migrations.AlterField(
            model_name='pledgedscrip',
            name='valuation_percent',
            field=models.FloatField(default=50, help_text="Bank's Allowable Margin %"),
        ),
    ]
