# Generated by Django 5.2.8 on 2025-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('absolute_change', models.FloatField(blank=True, null=True)),
                ('percentage_change', models.TextField(blank=True, null=True)),
                ('number_52_weeks_high', models.FloatField(blank=True, db_column='52_weeks_high', null=True)),
                ('number_52_weeks_low', models.FloatField(blank=True, db_column='52_weeks_low', null=True)),
                ('turnover_values', models.FloatField(blank=True, null=True)),
                ('turnover_volume', models.BigIntegerField(blank=True, null=True)),
                ('total_transaction', models.BigIntegerField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Indices',
                'db_table': 'indices',
            },
        ),
        migrations.CreateModel(
            name='Marcap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField(blank=True, null=True)),
                ('business_date', models.DateField(unique=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sensitive_market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('float_market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sensitive_float_market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Market Cap',
                'verbose_name_plural': 'Market Caps',
                'db_table': 'marcap',
            },
        ),
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('security_id', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('security_name', models.CharField(max_length=255)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_traded_quantity', models.BigIntegerField(blank=True, null=True)),
                ('total_traded_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fifty_two_week_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fifty_two_week_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated_time', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('average_traded_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stock Prices',
                'db_table': 'stock_prices',
                'unique_together': {('business_date', 'security_id')},
            },
        ),
    ]
