# Generated by Django 5.2.8 on 2025-11-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indices',
            options={'verbose_name_plural': 'Indices'},
        ),
        migrations.AlterField(
            model_name='marcap',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
