# Generated by Django 5.2.8 on 2025-11-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0002_alter_indices_options_alter_marcap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indices',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
