# Generated by Django 5.2.8 on 2025-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0003_alter_indices_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
