# Generated by Django 5.2.8 on 2025-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0004_indices_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcap',
            name='total_scrips_traded',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marcap',
            name='total_traded_shares',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marcap',
            name='total_transactions',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marcap',
            name='total_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='marcap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
