# Generated by Django 5.2.8 on 2025-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0005_marcap_total_scrips_traded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indices',
            name='absolute_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='indices',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='indices',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='indices',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='indices',
            name='number_52_weeks_high',
            field=models.DecimalField(blank=True, db_column='52_weeks_high', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='indices',
            name='number_52_weeks_low',
            field=models.DecimalField(blank=True, db_column='52_weeks_low', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='indices',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='indices',
            name='turnover_values',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
