# Generated by Django 5.2.8 on 2025-11-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0007_floorsheetraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('broker_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('tms_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'db_table': 'brokers',
            },
        ),
    ]
