# Generated by Django 5.2.8 on 2025-11-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0008_brokers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal_year', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bonus_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Tax for dividend purpose', max_digits=10, null=True)),
                ('total_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('book_closure_date', models.DateField(blank=True, null=True)),
                ('book_closure_status', models.CharField(blank=True, max_length=50, null=True)),
                ('distribution_date', models.DateField(blank=True, null=True)),
                ('bonus_listing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dividend History',
                'verbose_name_plural': 'Dividend Histories',
                'db_table': 'dividend_history',
                'ordering': ['-announcement_date', 'symbol'],
            },
        ),
    ]
