# Generated by Django 5.2.8 on 2025-11-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0009_dividendhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendhistory',
            name='right_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
