# Generated by Django 5.2.8 on 2025-11-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0009_dividendhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_date', models.DateField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('metric_item', models.CharField(max_length=255, verbose_name='Items')),
                ('metric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Metric',
                'verbose_name_plural': 'Company Metrics',
                'db_table': 'company_metrics',
                'unique_together': {('business_date', 'symbol', 'metric_item')},
            },
        ),
    ]
