# Generated by Django 5.2.8 on 2025-11-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0010_dividendhistory_right_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividendhistory',
            options={'verbose_name': 'Dividend History', 'verbose_name_plural': 'Dividend Histories'},
        ),
        migrations.AlterUniqueTogether(
            name='dividendhistory',
            unique_together={('symbol', 'fiscal_year', 'book_closure_date')},
        ),
    ]
