# Generated by Django 5.2.8 on 2025-11-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(db_index=True, help_text='Format: 2080/81', max_length=10, unique=True)),
                ('bs_start_year', models.IntegerField()),
                ('bs_start_month', models.IntegerField(default=4)),
                ('bs_start_day', models.IntegerField(default=1)),
                ('bs_end_year', models.IntegerField()),
                ('bs_end_month', models.IntegerField(default=3)),
                ('bs_end_day', models.IntegerField()),
                ('ad_start_date', models.DateField(db_index=True)),
                ('ad_end_date', models.DateField(db_index=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('total_days', models.IntegerField(help_text='Total days in fiscal year')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-bs_start_year'],
                'indexes': [models.Index(fields=['-bs_start_year'], name='nepali_date_bs_star_1a9303_idx'), models.Index(fields=['ad_start_date', 'ad_end_date'], name='nepali_date_ad_star_74826d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NepaliCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_year', models.IntegerField(db_index=True, help_text='Bikram Sambat Year')),
                ('month', models.IntegerField(choices=[(1, 'Baisakh'), (2, 'Jestha'), (3, 'Ashadh'), (4, 'Shrawan'), (5, 'Bhadra'), (6, 'Ashwin'), (7, 'Kartik'), (8, 'Mangsir'), (9, 'Poush'), (10, 'Magh'), (11, 'Falgun'), (12, 'Chaitra')], db_index=True)),
                ('days_in_month', models.IntegerField(help_text='Number of days in this month')),
                ('ad_start_date', models.DateField(blank=True, help_text='Gregorian date when this BS month starts', null=True)),
            ],
            options={
                'verbose_name': 'Nepali Calendar Entry',
                'verbose_name_plural': 'Nepali Calendar',
                'ordering': ['bs_year', 'month'],
                'indexes': [models.Index(fields=['bs_year', 'month'], name='nepali_date_bs_year_289b16_idx')],
                'unique_together': {('bs_year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_nepali', models.CharField(blank=True, max_length=200, null=True)),
                ('bs_year', models.IntegerField()),
                ('bs_month', models.IntegerField()),
                ('bs_day', models.IntegerField()),
                ('ad_date', models.DateField(db_index=True)),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('festival', 'Festival'), ('bank', 'Bank Holiday'), ('nepse', 'NEPSE Closed'), ('other', 'Other')], default='national', max_length=20)),
                ('is_nepse_trading_day', models.BooleanField(default=False, help_text='Is NEPSE open for trading on this holiday?')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['ad_date'],
                'indexes': [models.Index(fields=['ad_date'], name='nepali_date_ad_date_9f7c0c_idx'), models.Index(fields=['bs_year'], name='nepali_date_bs_year_04f347_idx')],
            },
        ),
        migrations.CreateModel(
            name='DateConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_year', models.IntegerField(db_index=True)),
                ('bs_month', models.IntegerField(db_index=True)),
                ('bs_day', models.IntegerField()),
                ('ad_date', models.DateField(db_index=True, unique=True)),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('is_weekend', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_conversions', to='nepali_datetime.fiscalyear')),
            ],
            options={
                'verbose_name': 'Date Conversion',
                'verbose_name_plural': 'Date Conversions',
                'ordering': ['ad_date'],
                'indexes': [models.Index(fields=['bs_year', 'bs_month', 'bs_day'], name='nepali_date_bs_year_f62ab0_idx'), models.Index(fields=['ad_date'], name='nepali_date_ad_date_dacba2_idx')],
                'unique_together': {('bs_year', 'bs_month', 'bs_day')},
            },
        ),
    ]
