# Generated by Django 5.2.8 on 2025-11-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepali_datetime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='ad_end_year',
            field=models.IntegerField(blank=True, help_text='Ending AD year', null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='ad_start_year',
            field=models.IntegerField(blank=True, help_text='Starting AD year', null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='fiscal_year_english',
            field=models.CharField(blank=True, db_index=True, help_text='English Fiscal Year Format: 2023/24', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='fiscal_year',
            field=models.CharField(db_index=True, help_text='Nepali Fiscal Year Format: 2080/81', max_length=10, unique=True),
        ),
    ]
