# Generated by Django 5.2.8 on 2025-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepali_datetime', '0002_fiscalyear_ad_end_year_fiscalyear_ad_start_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepaliDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_date', models.DateField(help_text='Gregorian Date', unique=True)),
                ('nepali_date', models.CharField(help_text='Format: YYYY-MM-DD', max_length=10, unique=True)),
                ('nepali_year', models.IntegerField()),
                ('nepali_month', models.IntegerField()),
                ('nepali_day', models.IntegerField()),
                ('day_of_week', models.IntegerField(help_text='1=Sunday, 7=Saturday')),
                ('day_name_english', models.CharField(blank=True, max_length=15, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nepali_year', 'nepali_month'], name='nepali_date_nepali__31e673_idx'), models.Index(fields=['english_date'], name='nepali_date_english_e545f9_idx')],
            },
        ),
    ]
