# Generated by Django 5.2.8 on 2025-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorsheetRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_no', models.CharField(max_length=100)),
                ('stock_symbol', models.CharField(max_length=20)),
                ('buyer', models.IntegerField()),
                ('seller', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('calculation_date', models.DateField()),
            ],
            options={
                'db_table': 'floorsheet_raw',
                'managed': False,
            },
        ),
    ]
