# Generated by Django 5.2.8 on 2025-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('nepse_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('script_ticker', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument', models.CharField(blank=True, max_length=50, null=True)),
                ('par_value', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
