# Generated by Django 5.2.8 on 2025-11-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listed_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorsheetRaw',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contract_no', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_symbol', models.CharField(max_length=255)),
                ('buyer', models.IntegerField(blank=True, null=True)),
                ('seller', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('calculation_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Floorsheet (Raw)',
                'verbose_name_plural': 'Floorsheet (Raw)',
                'db_table': 'floorsheet_raw',
                'managed': False,
            },
        ),
    ]
