# Generated by Django 5.2.8 on 2025-11-19 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listed_companies', '0002_floorsheetraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_symbol', models.CharField(db_index=True, help_text='References Companies.script_ticker', max_length=20)),
                ('action_type', models.CharField(choices=[('BONUS', 'Bonus Share'), ('RIGHT', 'Right Share'), ('DIVIDEND', 'Cash Dividend'), ('SPLIT', 'Stock Split'), ('MERGE', 'Stock Merger'), ('BUYBACK', 'Share Buyback'), ('IPO', 'Initial Public Offering'), ('FPO', 'Follow-on Public Offering'), ('DELISTING', 'Delisting'), ('AMALGAMATION', 'Amalgamation/Merger'), ('ACQUISITION', 'Acquisition'), ('CAPITAL_REDUCTION', 'Capital Reduction'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('announcement_date', models.DateField(blank=True, help_text='Date of announcement', null=True)),
                ('record_date', models.DateField(blank=True, help_text='Record date for eligibility', null=True)),
                ('book_closure_date', models.DateField(blank=True, help_text='Book closure date', null=True)),
                ('effective_date', models.DateField(blank=True, help_text='Date when action takes effect', null=True)),
                ('details', models.JSONField(blank=True, help_text="Structured data: e.g., {'ratio': '1:1', 'price': 100}", null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the corporate action', null=True)),
                ('affects_promoter_holding', models.BooleanField(default=False, help_text='Does this action affect promoter holdings?')),
                ('affects_public_holding', models.BooleanField(default=False, help_text='Does this action affect public holdings?')),
                ('regulatory_approval_date', models.DateField(blank=True, null=True)),
                ('source_document', models.CharField(blank=True, help_text='Reference to source document', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corporate Action',
                'verbose_name_plural': 'Corporate Actions',
                'db_table': 'corporate_actions',
                'ordering': ['-announcement_date', 'company_symbol'],
                'indexes': [models.Index(fields=['company_symbol', '-announcement_date'], name='corporate_a_company_30cc77_idx'), models.Index(fields=['action_type', '-announcement_date'], name='corporate_a_action__ef3ab0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LockInPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_symbol', models.CharField(db_index=True, help_text='References Companies.script_ticker', max_length=20)),
                ('lock_in_type', models.CharField(choices=[('PROMOTER', 'Promoter Lock-in'), ('MF_OTHERS', 'Mutual Fund & Others Lock-in'), ('IPO', 'IPO Lock-in'), ('FPO', 'FPO Lock-in'), ('RIGHT', 'Right Share Lock-in'), ('MERGER', 'Merger/Acquisition Lock-in'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('locked_shares', models.BigIntegerField(help_text='Number of shares under lock-in', validators=[django.core.validators.MinValueValidator(0)])),
                ('lock_in_start_date', models.DateField()),
                ('lock_in_end_date', models.DateField(db_index=True, help_text='Date when lock-in period ends')),
                ('shareholder_name', models.CharField(blank=True, help_text='Name of entity whose shares are locked', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Reason or details of lock-in', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether lock-in is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lock-in Period',
                'verbose_name_plural': 'Lock-in Periods',
                'db_table': 'lock_in_periods',
                'ordering': ['lock_in_end_date', 'company_symbol'],
                'indexes': [models.Index(fields=['company_symbol', 'lock_in_type'], name='lock_in_per_company_ab8440_idx'), models.Index(fields=['lock_in_end_date', 'is_active'], name='lock_in_per_lock_in_42d777_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShareholdingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_symbol', models.CharField(db_index=True, help_text='References Companies.script_ticker', max_length=20)),
                ('as_of_date', models.DateField(db_index=True, help_text='Date of this shareholding snapshot')),
                ('promoter_shares', models.BigIntegerField(blank=True, help_text='Number of promoter shares', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('promoter_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Promoter shareholding percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('public_shares', models.BigIntegerField(blank=True, help_text='Number of public shares', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('public_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Public shareholding percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('institutional_shares', models.BigIntegerField(blank=True, help_text='Number of institutional shares', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('institutional_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Institutional shareholding percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('other_shares', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('free_float_shares', models.BigIntegerField(blank=True, help_text='Shares available for public trading', null=True)),
                ('free_float_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Free float percentage', max_digits=5, null=True)),
                ('total_shares', models.BigIntegerField(blank=True, help_text='Total outstanding shares', null=True)),
                ('source', models.CharField(blank=True, help_text='Data source (e.g., NEPSE, AGM Report)', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shareholding Pattern',
                'verbose_name_plural': 'Shareholding Patterns',
                'db_table': 'shareholding_patterns',
                'ordering': ['-as_of_date', 'company_symbol'],
                'indexes': [models.Index(fields=['company_symbol', '-as_of_date'], name='shareholdin_company_2d4a3e_idx'), models.Index(fields=['as_of_date'], name='shareholdin_as_of_d_b10354_idx')],
                'unique_together': {('company_symbol', 'as_of_date')},
            },
        ),
    ]
