# Generated by Django 5.2.8 on 2025-11-11 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TREND', 'Trend'), ('MOMENTUM', 'Momentum'), ('VOLATILITY', 'Volatility'), ('VOLUME', 'Volume')], max_length=20)),
                ('description', models.TextField()),
                ('default_parameters', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'indicator_types',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('signal_type', models.CharField(choices=[('BUY', 'Strong Buy'), ('BUY_WEAK', 'Buy'), ('HOLD', 'Hold'), ('SELL_WEAK', 'Sell'), ('SELL', 'Strong Sell')], max_length=20)),
                ('strength', models.IntegerField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('business_date', models.DateField(db_index=True)),
                ('price_at_signal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('technical_summary', models.JSONField()),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('closed_price', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trading_signals',
                'ordering': ['-business_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('pattern_type', models.CharField(choices=[('DOJI', 'Doji'), ('HAMMER', 'Hammer'), ('SHOOTING_STAR', 'Shooting Star'), ('ENGULFING_BULL', 'Bullish Engulfing'), ('ENGULFING_BEAR', 'Bearish Engulfing'), ('MORNING_STAR', 'Morning Star'), ('EVENING_STAR', 'Evening Star'), ('HEAD_SHOULDERS', 'Head and Shoulders'), ('INVERSE_HEAD_SHOULDERS', 'Inverse Head and Shoulders'), ('DOUBLE_TOP', 'Double Top'), ('DOUBLE_BOTTOM', 'Double Bottom'), ('TRIANGLE_ASCENDING', 'Ascending Triangle'), ('TRIANGLE_DESCENDING', 'Descending Triangle'), ('WEDGE_RISING', 'Rising Wedge'), ('WEDGE_FALLING', 'Falling Wedge'), ('FLAG_BULL', 'Bullish Flag'), ('FLAG_BEAR', 'Bearish Flag')], max_length=50)),
                ('sentiment', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], max_length=20)),
                ('detected_date', models.DateField(db_index=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pattern_data', models.JSONField()),
                ('is_completed', models.BooleanField(default=False)),
                ('breakout_confirmed', models.BooleanField(default=False)),
                ('breakout_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chart_patterns',
                'indexes': [models.Index(fields=['symbol', '-detected_date'], name='chart_patte_symbol_0c3b81_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exit_date', models.DateField(null=True)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('profit_loss_percent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('holding_days', models.IntegerField(null=True)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_winner', models.BooleanField(null=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='technical_analysis.signal')),
            ],
            options={
                'db_table': 'signal_performance',
            },
        ),
        migrations.CreateModel(
            name='SupportResistanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('level_type', models.CharField(choices=[('SUPPORT', 'Support'), ('RESISTANCE', 'Resistance')], max_length=20)),
                ('price_level', models.DecimalField(decimal_places=2, max_digits=14)),
                ('strength', models.IntegerField()),
                ('first_touched', models.DateField()),
                ('last_touched', models.DateField()),
                ('touch_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('broken_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_resistance_levels',
                'indexes': [models.Index(fields=['symbol', 'is_active'], name='support_res_symbol_823aff_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('criteria', models.JSONField()),
                ('last_results', models.JSONField(null=True)),
                ('last_run', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technical_scans',
            },
        ),
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('strategy_type', models.CharField(max_length=50)),
                ('config', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('risk_level', models.CharField(default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicators_used', models.ManyToManyField(to='technical_analysis.indicatortype')),
            ],
            options={
                'verbose_name_plural': 'Trading Strategies',
                'db_table': 'trading_strategies',
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_analysis.tradingstrategy'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('symbols', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_watchlists',
            },
        ),
        migrations.CreateModel(
            name='IndicatorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('indicator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_analysis.indicatortype')),
            ],
            options={
                'db_table': 'indicator_cache',
                'unique_together': {('symbol', 'indicator_type', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('business_date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('value_json', models.JSONField(null=True)),
                ('parameters', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_analysis.indicatortype')),
            ],
            options={
                'db_table': 'indicator_values',
                'ordering': ['-business_date'],
                'indexes': [models.Index(fields=['symbol', 'business_date'], name='indicator_v_symbol_8ec297_idx'), models.Index(fields=['indicator_type', 'business_date'], name='indicator_v_indicat_e3a797_idx')],
                'unique_together': {('symbol', 'indicator_type', 'business_date')},
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('alert_type', models.CharField(choices=[('PRICE_ABOVE', 'Price Above'), ('PRICE_BELOW', 'Price Below'), ('CHANGE_PERCENT', 'Change Percent'), ('VOLUME_SPIKE', 'Volume Spike'), ('RSI_OVERBOUGHT', 'RSI Overbought'), ('RSI_OVERSOLD', 'RSI Oversold'), ('MACD_CROSSOVER', 'MACD Crossover'), ('MA_CROSSOVER', 'MA Crossover')], max_length=30)),
                ('condition_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(null=True)),
                ('triggered_price', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_alerts',
                'indexes': [models.Index(fields=['user', 'is_active'], name='price_alert_user_id_600b95_idx'), models.Index(fields=['symbol', 'is_active'], name='price_alert_symbol_5b11ba_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['symbol', '-business_date'], name='trading_sig_symbol_a0957f_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['signal_type', '-business_date'], name='trading_sig_signal__0fa8a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'name')},
        ),
    ]
