# Generated by Django.
# This file populates the IndicatorType and TradingStrategy models with initial data.

from django.db import migrations

def populate_indicators_and_strategies(apps, schema_editor):
    """
    Populates the database with default indicators and strategies
    that our services (IndicatorService, SignalService) know how to handle.
    """
    # Get the models from the app registry
    IndicatorType = apps.get_model('technical_analysis', 'IndicatorType')
    TradingStrategy = apps.get_model('technical_analysis', 'TradingStrategy')

    # --- 1. Populate IndicatorType ---
    
    IndicatorType.objects.bulk_create([
        IndicatorType(
            name="RSI",
            display_name="Relative Strength Index",
            category="MOMENTUM",
            description="Measures the speed and magnitude of price changes. Over 70 is overbought, under 30 is oversold.",
            default_parameters={"window": 14}
        ),
        IndicatorType(
            name="SMA_50",
            display_name="Simple Moving Average (50-day)",
            category="TREND",
            description="The 50-day simple moving average.",
            default_parameters={"window": 50}
        ),
        IndicatorType(
            name="SMA_200",
            display_name="Simple Moving Average (200-day)",
            category="TREND",
            description="The 200-day simple moving average, a key long-term trend indicator.",
            default_parameters={"window": 200}
        ),
        IndicatorType(
            name="MACD",
            display_name="Moving Average Convergence Divergence",
            category="TREND",
            description="Shows the relationship between two moving averages of a security's price.",
            default_parameters={"short_window": 12, "long_window": 26, "signal_window": 9}
        ),
        IndicatorType(
            name="Bollinger_Bands",
            display_name="Bollinger Bands",
            category="VOLATILITY",
            description="Measures volatility using a 20-day SMA and two standard deviations.",
            default_parameters={"window": 20, "std_dev": 2}
        ),
        # --- ADDED THIS ---
        IndicatorType(
            name="OBV",
            display_name="On-Balance Volume",
            category="VOLUME",
            description="Uses volume flow to predict changes in stock price. Relates volume to price change.",
            default_parameters={} # No window needed
        ),
    ])

    # --- 2. Populate TradingStrategy ---
    
    # We need to fetch the IndicatorType objects we just created to link them
    try:
        rsi_indicator = IndicatorType.objects.get(name="RSI")
        sma_50_indicator = IndicatorType.objects.get(name="SMA_50")
        sma_200_indicator = IndicatorType.objects.get(name="SMA_200")

        # Create the RSI Strategy
        rsi_strategy = TradingStrategy.objects.create(
            name="RSI Oversold/Overbought",
            description="Generates BUY signals when RSI crosses above 30 and SELL signals when it crosses below 70.",
            strategy_type="RSI_OVERSOLD",
            config={"rsi_params": {"window": 14}, "overbought": 70, "oversold": 30},
            risk_level="MEDIUM"
        )
        rsi_strategy.indicators_used.add(rsi_indicator)

        # Create the MA Crossover Strategy
        ma_cross_strategy = TradingStrategy.objects.create(
            name="Golden/Death Cross",
            description="Generates a BUY signal (Golden Cross) when SMA 50 crosses above SMA 200, and a SELL signal (Death Cross) when it crosses below.",
            strategy_type="MA_CROSSOVER",
            config={"short_window": 50, "long_window": 200},
            risk_level="HIGH"
        )
        ma_cross_strategy.indicators_used.add(sma_50_indicator, sma_200_indicator)
    
    except IndicatorType.DoesNotExist as e:
        print(f"Migration failed: Could not find prerequisite IndicatorType. {e}")


class Migration(migrations.Migration):

    dependencies = [
        # This depends on your first migration file
        ('technical_analysis', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(populate_indicators_and_strategies),
    ]