# Generated by Django.
# This file adds the OBV IndicatorType.

from django.db import migrations

def add_obv(apps, schema_editor):
    """
    Adds the On-Balance Volume (OBV) IndicatorType.
    """
    IndicatorType = apps.get_model('technical_analysis', 'IndicatorType')
    
    # Check if it already exists, just in case
    if not IndicatorType.objects.filter(name="OBV").exists():
        IndicatorType.objects.create(
            name="OBV",
            display_name="On-Balance Volume",
            category="VOLUME",
            description="Uses volume flow to predict changes in stock price. Relates volume to price change.",
            default_parameters={} # No window needed
        )

class Migration(migrations.Migration):

    dependencies = [
        # This depends on your previous migration file
        ('technical_analysis', '0002_populate_initial_data'), 
    ]

    operations = [
        migrations.RunPython(add_obv),
    ]