# Generated by Django 5.2.8 on 2025-11-10 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listed_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAdjustments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateTimeField(blank=True, null=True)),
                ('book_close_date', models.DateField()),
                ('adjustment_type', models.CharField(max_length=10)),
                ('adjustment_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('par_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('records_adjusted', models.IntegerField(blank=True, null=True)),
                ('adjustment_factor', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, to='listed_companies.companies', to_field='script_ticker')),
            ],
            options={
                'verbose_name': 'Price Adjustment',
                'verbose_name_plural': 'Price Adjustments',
                'db_table': 'price_adjustments',
            },
        ),
        migrations.CreateModel(
            name='StockPricesAdj',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('security_id', models.IntegerField(blank=True, null=True)),
                ('symbol', models.CharField(max_length=20)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('open_price_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('high_price_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('low_price_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('close_price_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adjustment_factor', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('average_traded_price_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fifty_two_week_high_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fifty_two_week_low_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Adjusted Stock Price',
                'verbose_name_plural': 'Adjusted Stock Prices',
                'db_table': 'stock_prices_adj',
                'unique_together': {('symbol', 'business_date')},
            },
        ),
    ]
