# Generated by Django 5.2.8 on 2025-11-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjustments_stock_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceadjustments',
            name='adjustment_type',
            field=models.CharField(choices=[('bonus', 'Bonus Share'), ('right', 'Right Share'), ('cash', 'Cash Dividend')], max_length=10),
        ),
    ]
