from django.db import models
from adjustments_stock_price.models import StockPricesAdj
from listed_companies.models import Companies
from .indicators import IndicatorType

class TradingStrategy(models.Model):
    """Define trading strategies"""
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    strategy_type = models.CharField(max_length=50)  # MA_CROSSOVER, RSI_DIVERGENCE
    
    # Strategy configuration
    config = models.JSONField()  # Strategy-specific parameters
    indicators_used = models.ManyToManyField(IndicatorType)
    
    is_active = models.BooleanField(default=True)
    risk_level = models.CharField(max_length=20, default='MEDIUM')  # LOW, MEDIUM, HIGH
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'trading_strategies'
        verbose_name_plural = 'Trading Strategies'


class Signal(models.Model):
    """Trading signals generated by strategies"""
    SIGNAL_TYPE_CHOICES = [
        ('BUY', 'Strong Buy'),
        ('BUY_WEAK', 'Buy'),
        ('HOLD', 'Hold'),
        ('SELL_WEAK', 'Sell'),
        ('SELL', 'Strong Sell'),
    ]
    
    symbol = models.CharField(max_length=20, db_index=True)
    strategy = models.ForeignKey(TradingStrategy, on_delete=models.CASCADE)
    
    signal_type = models.CharField(max_length=20, choices=SIGNAL_TYPE_CHOICES)
    strength = models.IntegerField()  # 1-10
    confidence = models.DecimalField(max_digits=5, decimal_places=2)  # 0-100%
    
    business_date = models.DateField(db_index=True)
    price_at_signal = models.DecimalField(max_digits=14, decimal_places=2)
    
    # Signal details
    reason = models.TextField()
    technical_summary = models.JSONField()  # Key indicator values at signal time
    
    # Target and stop loss (optional)
    target_price = models.DecimalField(max_digits=14, decimal_places=2, null=True)
    stop_loss = models.DecimalField(max_digits=14, decimal_places=2, null=True)
    
    is_active = models.BooleanField(default=True)
    closed_at = models.DateField(null=True, blank=True)
    closed_price = models.DecimalField(max_digits=14, decimal_places=2, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'trading_signals'
        indexes = [
            models.Index(fields=['symbol', '-business_date']),
            models.Index(fields=['signal_type', '-business_date']),
        ]
        ordering = ['-business_date', '-created_at']


class SignalPerformance(models.Model):
    """Track signal performance for backtesting"""
    signal = models.OneToOneField(Signal, on_delete=models.CASCADE)
    
    entry_date = models.DateField()
    entry_price = models.DecimalField(max_digits=14, decimal_places=2)
    
    exit_date = models.DateField(null=True)
    exit_price = models.DecimalField(max_digits=14, decimal_places=2, null=True)
    
    profit_loss = models.DecimalField(max_digits=14, decimal_places=2, null=True)
    profit_loss_percent = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    
    holding_days = models.IntegerField(null=True)
    max_drawdown = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    
    is_winner = models.BooleanField(null=True)
    
    class Meta:
        db_table = 'signal_performance'