# Generated by Django 5.2.8 on 2025-11-16 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listed_companies', '0002_floorsheetraw'),
        ('nepse_data', '0011_alter_dividendhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Chq Issue', 'Cheque Issue'), ('Pledge Charge', 'Pledge Charge'), ('Misc(+)', 'Misc (+)'), ('Misc(-)', 'Misc (-)'), ('Balance b/d', 'Balance b/d')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nepse_data.brokers', to_field='broker_no')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('BUY', 'BUY'), ('SALE', 'SALE'), ('BONUS', 'BONUS'), ('RIGHT', 'RIGHT'), ('IPO', 'IPO'), ('CASH', 'CASH'), ('CONVERSION(+)', 'CONVERSION(+)'), ('CONVERSION(-)', 'CONVERSION(-)'), ('SUSPENSE(+)', 'SUSPENSE(+)'), ('SUSPENSE(-)', 'SUSPENSE(-)'), ('Balance b/d', 'Balance b/d')], max_length=20)),
                ('kitta', models.IntegerField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, max_length=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Rate')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Comm. rate (%)')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Comm. Amt.')),
                ('nepse_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sebon_regularity_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('broker_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sebo_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cgt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='CGT')),
                ('dp_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='DP Fee')),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('script', models.CharField(blank=True, help_text='Auto-filled from Symbol', max_length=255)),
                ('sector', models.CharField(blank=True, help_text='Auto-filled from Symbol', max_length=100)),
                ('eff_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated (Billed Amount / Kitta)', max_digits=20, null=True, verbose_name='Effective Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listed_companies.companies', to_field='script_ticker')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
