# Generated by Django 5.2.8 on 2025-11-12 14:12

import django.db.models.deletion
import my_portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listed_companies', '0002_floorsheetraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('unique_id', models.CharField(default=my_portfolio.models.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('script', models.CharField(blank=True, editable=False, max_length=255)),
                ('sector', models.CharField(blank=True, editable=False, max_length=100)),
                ('transaction_type', models.CharField(choices=[('Balance b/d', 'Balance b/d'), ('BUY', 'BUY'), ('SALE', 'SALE'), ('BONUS', 'BONUS'), ('IPO', 'IPO'), ('RIGHT', 'RIGHT'), ('CONVERSION(+)', 'CONVERSION(+)'), ('CONVERSION(-)', 'CONVERSION(-)'), ('SUSPENSE(+)', 'SUSPENSE(+)'), ('SUSPENSE(-)', 'SUSPENSE(-)')], max_length=20)),
                ('kitta', models.PositiveIntegerField()),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('broker', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.PROTECT, to='listed_companies.companies', to_field='script_ticker')),
            ],
            options={
                'verbose_name': 'Portfolio Transaction',
                'verbose_name_plural': 'Portfolio Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
