# Generated by Django 5.2.8 on 2025-11-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listed_companies', '0003_corporateaction_lockinperiod_shareholdingpattern'),
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DematAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demat_number', models.CharField(help_text='16-digit BOID', max_length=16, unique=True)),
                ('capital_name', models.CharField(help_text='Name of the Capital/DP (e.g., Nabil Investment Banking)', max_length=255)),
                ('owner_name', models.CharField(blank=True, help_text='Name of the account holder', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeroShareHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pledge_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lockin_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('freeze_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('free_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('demat_pending', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demat_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='my_portfolio.demataccount')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listed_companies.companies', to_field='script_ticker')),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('demat_account', 'symbol')},
            },
        ),
    ]
