# Generated by Django 5.2.8 on 2025-11-14 06:42

import django.db.models.deletion
import my_portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
        ('nepse_data', '0008_brokers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerTransaction',
            fields=[
                ('unique_id', models.CharField(default=my_portfolio.models.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('action', models.CharField(choices=[('Balance b/d', 'Balance b/d'), ('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Chq Issue', 'Chq Issue'), ('Pledge Charge', 'Pledge Charge'), ('Buy C/O', 'Buy C/O'), ('Sale C/O', 'Sale C/O'), ('Misc(+)', 'Misc(+)'), ('Misc(-)', 'Misc(-)')], max_length=20, verbose_name='Action')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(db_column='broker_no', on_delete=django.db.models.deletion.PROTECT, to='nepse_data.brokers', to_field='broker_no', verbose_name='Broker')),
            ],
            options={
                'verbose_name': 'Broker Transaction',
                'verbose_name_plural': 'Broker Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
