# Generated by Django 5.2.8 on 2025-11-20 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listed_companies', '0003_corporateaction_lockinperiod_shareholdingpattern'),
        ('my_portfolio', '0002_demataccount_meroshareholding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meroshareholding',
            options={'ordering': ['-snapshot_date', 'symbol']},
        ),
        migrations.AlterUniqueTogether(
            name='meroshareholding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meroshareholding',
            name='snapshot_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date this balance represents'),
        ),
        migrations.AlterUniqueTogether(
            name='meroshareholding',
            unique_together={('demat_account', 'symbol', 'snapshot_date')},
        ),
    ]
